//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuFlowGateway.TestApplication.CFGateway {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow", ConfigurationName="CFGateway.ExecuteFlowWebServiceSoap")]
    public interface ExecuteFlowWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name flowID from namespace http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow/ExecuteFlow", ReplyAction="*")]
        CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponse ExecuteFlow(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow/ExecuteFlow", ReplyAction="*")]
        System.Threading.Tasks.Task<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponse> ExecuteFlowAsync(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest request);
        
        // CODEGEN: Generating message contract since element name flowID from namespace http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow/ExecuteFlowWithReturn", ReplyAction="*")]
        CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponse ExecuteFlowWithReturn(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow/ExecuteFlowWithReturn", ReplyAction="*")]
        System.Threading.Tasks.Task<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponse> ExecuteFlowWithReturnAsync(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFlow", Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow", Order=0)]
        public CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequestBody Body;
        
        public ExecuteFlowRequest() {
        }
        
        public ExecuteFlowRequest(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow")]
    public partial class ExecuteFlowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string flowID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values;
        
        public ExecuteFlowRequestBody() {
        }
        
        public ExecuteFlowRequestBody(string flowID, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values) {
            this.flowID = flowID;
            this.keys = keys;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFlowResponse", Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow", Order=0)]
        public CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponseBody Body;
        
        public ExecuteFlowResponse() {
        }
        
        public ExecuteFlowResponse(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExecuteFlowResponseBody {
        
        public ExecuteFlowResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFlowWithReturnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFlowWithReturn", Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow", Order=0)]
        public CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequestBody Body;
        
        public ExecuteFlowWithReturnRequest() {
        }
        
        public ExecuteFlowWithReturnRequest(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow")]
    public partial class ExecuteFlowWithReturnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string flowID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values;
        
        public ExecuteFlowWithReturnRequestBody() {
        }
        
        public ExecuteFlowWithReturnRequestBody(string flowID, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values) {
            this.flowID = flowID;
            this.keys = keys;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteFlowWithReturnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteFlowWithReturnResponse", Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow", Order=0)]
        public CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponseBody Body;
        
        public ExecuteFlowWithReturnResponse() {
        }
        
        public ExecuteFlowWithReturnResponse(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.itsoftware.no/2010/CompuFlow/ExecuteFlow")]
    public partial class ExecuteFlowWithReturnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ExecuteFlowWithReturnResult;
        
        public ExecuteFlowWithReturnResponseBody() {
        }
        
        public ExecuteFlowWithReturnResponseBody(byte[] ExecuteFlowWithReturnResult) {
            this.ExecuteFlowWithReturnResult = ExecuteFlowWithReturnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecuteFlowWebServiceSoapChannel : CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteFlowWebServiceSoapClient : System.ServiceModel.ClientBase<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap>, CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap {
        
        public ExecuteFlowWebServiceSoapClient() {
        }
        
        public ExecuteFlowWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecuteFlowWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteFlowWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteFlowWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponse CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap.ExecuteFlow(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest request) {
            return base.Channel.ExecuteFlow(request);
        }
        
        public void ExecuteFlow(string flowID, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values) {
            CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest inValue = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest();
            inValue.Body = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequestBody();
            inValue.Body.flowID = flowID;
            inValue.Body.keys = keys;
            inValue.Body.values = values;
            CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponse retVal = ((CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap)(this)).ExecuteFlow(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponse> CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap.ExecuteFlowAsync(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest request) {
            return base.Channel.ExecuteFlowAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowResponse> ExecuteFlowAsync(string flowID, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values) {
            CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest inValue = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequest();
            inValue.Body = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowRequestBody();
            inValue.Body.flowID = flowID;
            inValue.Body.keys = keys;
            inValue.Body.values = values;
            return ((CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap)(this)).ExecuteFlowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponse CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap.ExecuteFlowWithReturn(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest request) {
            return base.Channel.ExecuteFlowWithReturn(request);
        }
        
        public byte[] ExecuteFlowWithReturn(string flowID, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values) {
            CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest inValue = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest();
            inValue.Body = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequestBody();
            inValue.Body.flowID = flowID;
            inValue.Body.keys = keys;
            inValue.Body.values = values;
            CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponse retVal = ((CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap)(this)).ExecuteFlowWithReturn(inValue);
            return retVal.Body.ExecuteFlowWithReturnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponse> CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap.ExecuteFlowWithReturnAsync(CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest request) {
            return base.Channel.ExecuteFlowWithReturnAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnResponse> ExecuteFlowWithReturnAsync(string flowID, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString keys, CompuFlowGateway.TestApplication.CFGateway.ArrayOfString values) {
            CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest inValue = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequest();
            inValue.Body = new CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWithReturnRequestBody();
            inValue.Body.flowID = flowID;
            inValue.Body.keys = keys;
            inValue.Body.values = values;
            return ((CompuFlowGateway.TestApplication.CFGateway.ExecuteFlowWebServiceSoap)(this)).ExecuteFlowWithReturnAsync(inValue);
        }
    }
}
